stages:
  - build

build-slm-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  variables:
    CUSTOM_REGISTRY: "gitlab-registry.dev.anansecloud.com"
    CUSTOM_REGISTRY_IMAGE: "gitlab-registry.dev.anansecloud.com/ml/smoke-test"
    KUBERNETES_NAMESPACE: "gitlab-runner"
    KUBERNETES_SERVICE_ACCOUNT: "gitlab-runner"

  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CUSTOM_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json

  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CUSTOM_REGISTRY_IMAGE}:latest"
      --destination "${CUSTOM_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --skip-unused-stages
      --insecure
      --insecure-registry "${CUSTOM_REGISTRY}"
      --skip-tls-verify
      --registry-mirror "${CUSTOM_REGISTRY}"
      --push-retry 5
      --compression gzip
      --compression-level 1

  rules:
    - if: $CI_COMMIT_BRANCH == "main"`